# Generated by Django 5.2.7 on 2025-11-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version: mobile-phones-tablets', unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., iPhone 15 Pro Max', max_length=50, verbose_name='Product Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Full Product Description')),
                ('short_description', models.TextField(help_text='Brief summary for listings', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GHS', max_length=20)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('stock_quantity', models.IntegerField(help_text='How many in stock')),
                ('low_stock_threshold', models.IntegerField(help_text="When to show 'Low Stock' warning")),
                ('track_inventory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre Order'), ('discontinued', 'Discontinued')], default='out_of_stock', max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('meta_title', models.CharField(max_length=50)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
